export const seedUsers = [
  { email: 'fakebuyer', password: 'password', walletBalance: 79, isAdmin: false, isInstructor: false },
  { email: 'admin', password: 'adminpass', walletBalance: 5, isAdmin: true, isInstructor: false },
  { email: 'instructor', password: 'password', walletBalance: 3, isAdmin: false, isInstructor: true },
  { email: 'cindy', password: 'cindy', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'luga', password: 'luga', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'tatyana', password: 'tatyana', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'sanzana', password: 'sanzana', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'shimon', password: 'shimon', walletBalance: 3, isAdmin: false, isInstructor: false },
  
  { email: 'xiaohualei', password: 'xiaohualei', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'katywangbai', password: 'katywangbai', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'mikelian', password: 'mikelian', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'maritzacastaneda', password: 'maritzacastaneda', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'chomyathnin', password: 'chomyathnin', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'taniagalioti', password: 'taniagalioti', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'meriamjirari', password: 'meriamjirari', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'veronikaivaniuk', password: 'veronikaivaniuk', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'tamjuddin', password: 'tamjuddin', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'xiangtingliu', password: 'xiangtingliu', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'kesookriashvili', password: 'kesookriashvili', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'albertcuello', password: 'albertcuello', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'maggiechen', password: 'maggiechen', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'midaliaabreu', password: 'midaliaabreu', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'guesnonrobillard', password: 'guesnonrobillard', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'wilannremigoso', password: 'wilannremigoso', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'arronmathew', password: 'arronmathew', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'tuckerpronko', password: 'tuckerpronko', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'tazmintahia', password: 'tazmintahia', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'isabeldonohue', password: 'isabeldonohue', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'brandonmartinez', password: 'brandonmartinez', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'derekdong', password: 'derekdong', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'esmeraldasufaj', password: 'esmeraldasufaj', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'ronelfranco', password: 'ronelfranco', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'sukanyasingha', password: 'sukanyasingha', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'vivianfengng', password: 'vivianfengng', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'pedrorodriguez', password: 'pedrorodriguez', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'sachitoprani', password: 'sachitoprani', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'yufendeng', password: 'yufendeng', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'idallisulloa', password: 'idallisulloa', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'marapatucelli', password: 'marapatucelli', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'elliotchen', password: 'elliotchen', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'komronrustamov', password: 'komronrustamov', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'avashi', password: 'avashi', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'jenniechen', password: 'jenniechen', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'amymurphy', password: 'amymurphy', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'tseringlama', password: 'tseringlama', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'felixperez', password: 'felixperez', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'jaclyntobias', password: 'jaclyntobias', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'angeltandon', password: 'angeltandon', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'tusharbudhram', password: 'tusharbudhram', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'robertcarnival', password: 'robertcarnival', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'junhuilin', password: 'junhuilin', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'arielmisvaldez', password: 'arielmisvaldez', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'danaylli', password: 'danaylli', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'salvadorflores', password: 'salvadorflores', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'henrikholtsberher', password: 'henrikholtsberher', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'arthurleon', password: 'arthurleon', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'halilsevencan', password: 'halilsevencan', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'arlenysantanaagramonte', password: 'arlenysantanaagramonte', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'kenomiguelluga', password: 'kenomiguelluga', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'justinmarupov', password: 'justinmarupov', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'jolindong', password: 'jolindong', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'binni', password: 'binni', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'jadecepedatapia', password: 'jadecepedatapia', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'jessicawu', password: 'jessicawu', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'reannerebello', password: 'reannerebello', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'tianyuchen', password: 'tianyuchen', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'christianreyes', password: 'christianreyes', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'gordonvo', password: 'gordonvo', walletBalance: 3, isAdmin: false, isInstructor: false },

  { email: 'jessicaxie', password: 'jessicaxie', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'kristendey', password: 'kristendey', walletBalance: 3, isAdmin: false, isInstructor: false },
  { email: 'kaifali', password: 'kaifali', walletBalance: 3, isAdmin: false, isInstructor: false },
];
